/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (node-sequelize) on 2018-06-12 18:19:49.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

module.exports = function(sequelize, DataTypes) {
    return sequelize.define('Activity', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        hash: {
            type: DataTypes.STRING(40)
        },
        imsi: {
            type: DataTypes.STRING(20)
        },
        type: {
            type: DataTypes.SMALLINT
        },
        address: {
            type: DataTypes.STRING(20)
        },
        data: {
            type: DataTypes.STRING(1024)
        },
        status: {
            type: DataTypes.SMALLINT
        },
        time: {
            type: DataTypes.DATE
        }
    }, {
        tableName: 'activity',
        indexes: [
            {
                name: 'hash',
                fields: ['hash']
            },
            {
                name: 'imsi',
                fields: ['imsi']
            },
            {
                name: 'type',
                fields: ['type']
            },
            {
                name: 'status',
                fields: ['status']
            }
        ],
        timestamps: false,
        underscored: true,
        syncOnAssociation: false
    });
}