/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.0-dev (node-sequelize6 dev) on 2020-07-19 18:18:14.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize');

class Pdu extends Model {
}

module.exports = (sequelize) => {
    return Pdu.init({
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        hash: {
            type: DataTypes.STRING(40)
        },
        imsi: {
            type: DataTypes.STRING(20)
        },
        dir: {
            type: DataTypes.SMALLINT
        },
        address: {
            type: DataTypes.STRING(20)
        },
        pdu: {
            type: DataTypes.STRING(1024)
        },
        mr: {
            type: DataTypes.SMALLINT
        },
        code: {
            type: DataTypes.INTEGER
        },
        sent: {
            type: DataTypes.DATE
        },
        received: {
            type: DataTypes.DATE
        },
        time: {
            type: DataTypes.DATE
        }
    }, {
        sequelize: sequelize,
        modelName: 'Pdu',
        tableName: 'pdu',
        indexes: [
            {
                name: 'hash',
                fields: ['hash']
            },
            {
                name: 'imsi',
                fields: ['imsi']
            },
            {
                name: 'pdu',
                fields: ['pdu']
            }
        ],
        timestamps: false,
        underscored: true,
        syncOnAssociation: false
    });
}