/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (node-sequelize) on 2018-06-12 18:19:49.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

module.exports = function(sequelize, DataTypes) {
    return sequelize.define('Pdu', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        hash: {
            type: DataTypes.STRING(40)
        },
        imsi: {
            type: DataTypes.STRING(20)
        },
        dir: {
            type: DataTypes.SMALLINT
        },
        address: {
            type: DataTypes.STRING(20)
        },
        pdu: {
            type: DataTypes.STRING(1024)
        },
        mr: {
            type: DataTypes.SMALLINT
        },
        code: {
            type: DataTypes.INTEGER
        },
        sent: {
            type: DataTypes.DATE
        },
        received: {
            type: DataTypes.DATE
        },
        time: {
            type: DataTypes.DATE
        }
    }, {
        tableName: 'pdu',
        indexes: [
            {
                name: 'hash',
                fields: ['hash']
            },
            {
                name: 'imsi',
                fields: ['imsi']
            },
            {
                name: 'pdu',
                fields: ['pdu']
            }
        ],
        timestamps: false,
        underscored: true,
        syncOnAssociation: false
    });
}