/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (node-sequelize) on 2018-06-12 18:19:49.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

module.exports = function(sequelize, DataTypes) {
    return sequelize.define('PduReport', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        imsi: {
            type: DataTypes.STRING(20)
        },
        pdu: {
            type: DataTypes.STRING(1024)
        },
        time: {
            type: DataTypes.DATE
        }
    }, {
        tableName: 'pdu_report',
        indexes: [
            {
                name: 'imsi',
                fields: ['imsi']
            },
            {
                name: 'pdu',
                fields: ['pdu']
            }
        ],
        timestamps: false,
        underscored: true,
        syncOnAssociation: false
    });
}