/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.0-dev (node-sequelize6 dev) on 2020-07-19 18:18:14.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize');

class PduReport extends Model {
}

module.exports = (sequelize) => {
    return PduReport.init({
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        imsi: {
            type: DataTypes.STRING(20)
        },
        pdu: {
            type: DataTypes.STRING(1024)
        },
        time: {
            type: DataTypes.DATE
        }
    }, {
        sequelize: sequelize,
        modelName: 'PduReport',
        tableName: 'pdu_report',
        indexes: [
            {
                name: 'imsi',
                fields: ['imsi']
            },
            {
                name: 'pdu',
                fields: ['pdu']
            }
        ],
        timestamps: false,
        underscored: true,
        syncOnAssociation: false
    });
}